### ISSUE TITLE
Using memento.<...> in launch.json for debugging

### ISSUE THREAD

**Issue by bauersimon** [ChaosinaCan/vscode-memento-inputs#14]
When I create a `launch.json` for debugging and try to use `memento.promptString` as a type for an input, I receive an error when launching with the debug configuration: `Input variable "foo" can only be of type "promptString", "pickString" or "command".`

**Comment by wuxu92** [comment]
You should use type as `command` and set command to `memento.promptString` like below:

```
       {
            "id": "id-for-mem",
            "type": "command",
            "command": "memento.promptString",
            "args": {
                "id": "id-for-mem",
                "description": "Test pattern to run",
            }
        }
```

**Comment by bauersimon** [comment]
It works. Sorry for not applying the documentation properly.
